name: Docker Image Deployment

on:
  push:
    branches: [ "master" ]

permissions: write-all

jobs:
  publish-nuit-info-image:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build Docker image
        run: |
          docker build -t ghcr.io/williammadie/nuit-info:latest .
          docker run -d -p 80:80 ghcr.io/williammadie/nuit-info:latest
          docker push ghcr.io/williammadie/nuit-info:latest

